micronaut:
  application:
    name: row-level-security-test
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
      keys:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: eiRDJkYpSEBNY1FmVGpXblpyNHU3eCFBJUQqRy1LYU4=
              base64: true
              jws-algorithm: HS256
      roles-name: 'scopes'

authorization-policies:
  order-full:
    scopes:
      - 'order.full'
      - 'self:order.full'
  order-readonly:
    scopes:
      - 'order.readonly'
      - 'self:order.readonly'
      - 'order.full'
      - 'self:order.full'
  user-full:
    scopes:
      - 'user.full'
      - 'self:user.full'
  user-readonly:
    scopes:
      - 'user.readonly'
      - 'self:user.readonly'
      - 'user.full'
      - 'self:user.full'


datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/row-level-security'
    username: ripalbarot
    password: strongPassword
    schema-generate: CREATE_DROP

jpa:
  entity-scan:
    packages: 'com.personal.models'
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
